version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: pg-promise
    versions:
    - 10.9.2
    - 10.9.4
    - 10.9.5
  - dependency-name: notistack
    versions:
    - 1.0.3
    - 1.0.4
    - 1.0.5
